In [1]:
import torch

In [4]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Tensors
A tensor is generalized matrix. It is a multidimensional array. A tensor can be 0-dimensional, 1-dimensional, 2-dimensional, 3-dimensional, etc. The number of dimensions is the rank of the tensor. A 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector, a 2-dimensional tensor is a matrix, and a 3-dimensional tensor is a cube, etc.

In [5]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
# set device and dtype
x = torch.tensor(
    [[1,2,3,4],[5,6,7,8]], 
    dtype=torch.float32, 
    device=device, 
    requires_grad=True # for autograd
)
x

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)

In [8]:
# tensor properties
print(x.shape)
print(x.size())
print(x.dtype)
print(x.device)
print(x.requires_grad)

torch.Size([2, 4])
torch.Size([2, 4])
torch.float32
cpu
True


In [9]:
# other initialization methods
x = torch.empty(size=(3,3)) # uninitialized matrix
x

tensor([[-1.0582e-25,  1.4041e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [11]:
x = torch.zeros(size=(3,3)) # zeros matrix
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x = torch.ones(size=(3,3)) # ones matrix
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x = torch.rand(size=(3,3)) # uniform random
x

tensor([[0.3221, 0.7170, 0.3253],
        [0.2376, 0.0088, 0.3216],
        [0.5780, 0.2947, 0.9424]])

In [15]:
x = torch.eye(5,5) # identity matrix
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
# arrange 
x = torch.arange(start=0, end=5, step=1) # 1D tensor
x

tensor([0, 1, 2, 3, 4])

In [17]:
# lin space
x = torch.linspace(start=0.1, end=1, steps=10) # 1D tensor
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [18]:
x = torch.empty(size=(1,5)).normal_(mean=0, std=1) # normal distribution
x

tensor([[-0.9067,  1.0137,  0.8444,  0.1775, -0.3935]])

In [19]:
x = torch.empty(size=(1,5)).uniform_(0,1) # uniform distribution
x

tensor([[0.3831, 0.9514, 0.8812, 0.6539, 0.2834]])

In [20]:
x = torch.diag(torch.ones(3)) # diagonal matrix (3X3) similar to eye
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
# initialize and convert to tensor
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)


# Tensor Mathematics

In [28]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])


In [29]:
# addition
sum_1 = x + y
sum_1

tensor([10, 10, 10])

In [30]:
sum_2 = torch.add(x, y)
sum_2

tensor([10, 10, 10])

In [31]:
# subtraction
sub_1 = x - y
sub_1

tensor([-8, -6, -4])

In [32]:
# division
div_1 = torch.true_divide(x, y)
div_1

tensor([0.1111, 0.2500, 0.4286])

In [33]:
# inplace operation
t = torch.zeros(3)
t.add_(x)


tensor([1., 2., 3.])

In [34]:
# exponentiation
z = x.pow(2)
z

tensor([1, 4, 9])

In [35]:
z = x ** 2 # another way of exponentiation
z

tensor([1, 4, 9])

In [36]:
# simple comparison
z = x > 0
z

tensor([True, True, True])

In [37]:
z = x < 0
z

tensor([False, False, False])

In [38]:
# matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
x3

tensor([[2.7018, 1.4749, 1.5037],
        [2.1308, 0.9702, 1.1690]])

In [39]:
x4 = x1.mm(x2) # another way of multiplying
x4

tensor([[2.7018, 1.4749, 1.5037],
        [2.1308, 0.9702, 1.1690]])

In [98]:
# matrix exponentiation
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)
matrix_exp.shape

torch.Size([5, 5])

In [41]:
# elementwise multiplication
z = x * y 
z

tensor([ 9, 16, 21])

In [42]:
# dot product
z = torch.dot(x,y)
z

tensor(46)

In [97]:
# batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)
out_bmm.shape

torch.Size([32, 10, 30])

In [45]:
# example of broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5)) # this vector would be expanded automatically to match the other one for the operation below

z = x1 - x2
z

tensor([[ 0.1202, -0.8134,  0.0031,  0.3734, -0.0014],
        [ 0.0179,  0.0891, -0.1913,  0.2542,  0.8200],
        [-0.0159, -0.7583,  0.4559,  0.2402,  0.4899],
        [-0.1687, -0.2010, -0.1598, -0.0447, -0.1392],
        [ 0.2269, -0.6486, -0.1390, -0.0822,  0.0889]])

In [46]:
z = x1 ** x2
z

tensor([[0.7801, 0.0269, 0.6948, 0.9417, 0.7555],
        [0.7196, 0.9293, 0.5244, 0.8743, 0.9947],
        [0.6957, 0.1080, 0.9266, 0.8661, 0.9365],
        [0.5339, 0.6782, 0.5591, 0.6786, 0.4639],
        [0.8311, 0.2396, 0.5799, 0.6501, 0.8107]])

In [48]:
# other useful operations
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [49]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor(3), tensor(2))

In [62]:
values, indices = x.max(dim=0)
values, indices

(tensor(True), tensor(0))

In [50]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor(1), tensor(0))

In [51]:
absolute_val = torch.abs(x)
absolute_val

tensor([1, 2, 3])

In [52]:
arg_max = torch.argmax(x)
arg_max

tensor(2)

In [53]:
arg_min = torch.argmin(x)
arg_min

tensor(0)

In [54]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [55]:
z = torch.eq(x, y)
z

tensor([False, False, False])

In [57]:
# sort 
sorted_y, indices = torch.sort(y, dim=0, descending=False)
sorted_y, indices

(tensor([7, 8, 9]), tensor([2, 1, 0]))

In [58]:
z = torch.clamp(x, min=0, max=10) # clamp every values less than 0 to zero and any value > 10 to 10
z

tensor([1, 2, 3])

In [59]:
x= torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x)
z

tensor(True)

In [60]:
z = torch.all(x)
z

tensor(False)

# Indexing

In [64]:
batch_size = 10
features = 25
x= torch.rand((batch_size, features))
x[0].shape

torch.Size([25])

In [65]:
x[:, 0].shape

torch.Size([10])

In [67]:
# get the third example
x[2, 0:10]

tensor([0.9856, 0.8409, 0.5737, 0.6209, 0.6445, 0.1906, 0.7265, 0.0268, 0.2684,
        0.0730])

In [68]:
x[0,0] = 100

In [69]:
# fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [72]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
x[rows, cols].shape

torch.Size([2])

In [76]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [77]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [78]:
# other useful operations
torch.where(x > 5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [79]:
torch.tensor([0,0,1,2,2,3,4]).unique()

tensor([0, 1, 2, 3, 4])

In [80]:
x.ndimension() # check the dimensions

1

In [81]:
# count the number in x
x.numel()

10

# Reshape

In [82]:
x = torch.arange(9)
x_3x3 = x.view(3,3) # view acts on contiguous tensors - saved in memory with pointers
x_3x3.shape

torch.Size([3, 3])

In [84]:
x_3x3 = x.reshape(3,3)
x_3x3.shape

torch.Size([3, 3])

In [85]:
y = x_3x3.t() # a long vector
y # view would not work on this, reshape works here better
# or you can use contiguous.view(9) to achieve the same effect

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [86]:
x1= torch.rand((2,5))
x2=torch.rand((2,5))

torch.cat((x1,x2), dim=0).shape

torch.Size([4, 5])

In [87]:
torch.cat((x1,x2), dim=1).shape

torch.Size([2, 10])

In [88]:
z = x1.view(-1) # unroll it or flatten it
z.shape

torch.Size([10])

In [92]:
batch = 64
x = torch.rand((batch, 2,5))
z = x.view(batch, -1) # keep batch and flatten the rest
z.shape

torch.Size([64, 10])

In [91]:
# keep the batch and switch the axis
z = x.permute(0,2,1) # special case of transpose with more dimensions
z.shape

torch.Size([64, 5, 2])

In [93]:
x = torch.arange(10)
x.unsqueeze(0).shape

torch.Size([1, 10])

In [94]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [95]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.shape

torch.Size([1, 1, 10])

In [96]:
z = x.squeeze(0)
z.shape

torch.Size([1, 10])